### ISSUE TITLE
F1值问题

### ISSUE THREAD

**Issue by agrass1314a** [conglei2XU/Global-Context-Mechanism#22]
作者您好，我多次运行您的代码后，（参数与您readme设置的一致），weibo数据集得到的test f1值是0.67，valid f1是0.69，请问哪里有问题吗

**Comment by conglei2XU** [comment]
您好，不同的显卡LSTM以及后面global context 的学习率可能需要调整下，后面的global context 尽量小一些1e-3, 5e-4, 1e-4, LSTM一般1e-3, 5e-3。

**Comment by agrass1314a** [comment]
感谢您的回复，可能因为我使用的服务器是Maxos的mps，根据您的建议改变global context数值后，已经达到您论文的结果，感谢您！！！！

**Comment by agrass1314a** [comment]
感谢您的回复，根据您的建议，我修改了global context 参数值，达到了您论文的结果（可能是因为我使用Macos的mps进行训练造成的问题），再次感谢您

**Comment by conglei2XU** [comment]
不用客气，这个仓库还在更新，后面会支持不同的transformers-based模型以及bert  crf。
