### ISSUE TITLE
如何讓model跑weibo資料集?

### ISSUE THREAD

**Issue by elaine35002** [conglei2XU/Global-Context-Mechanism#24]
您好 我嘗試使用
```
python main.py --mode light --model_name lstm --batch_size 32 --task_type NER --dataset_name Weibo --use_context True  
```
weibo的dataset dataset我已下載到data路徑底下，且在main.py也已更改ner_reader_cn，在config.py中也已加上關於weibo資料及的實體標籤部分，但在訓練時出現的f1 score的分數仍皆為0:
```
INFO:__main__:Epoch: 1   Global step: 43         Avgloss: 1.07
INFO:__main__:Overall results: 
INFO:__main__:precision 0.0000 recall 0.0000 f1 0.0000
INFO:__main__:fine_grained_f1: 
INFO:__main__:--------------------------------------------------
Epoch: 2: Percentage: 43/43 Loss: 1.05: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:01<00:00, 22.60it/s]
INFO:__main__:--------------------------------------------------
INFO:__main__:Epoch: 2   Global step: 86         Avgloss: 1.05
INFO:__main__:Overall results: 
INFO:__main__:precision 0.0000 recall 0.0000 f1 0.0000
INFO:__main__:fine_grained_f1: 
INFO:__main__:--------------------------------------------------
Epoch: 3: Percentage: 43/43 Loss: 1.03: 100%|█
```

請問該如何修正呢?

**Comment by conglei2XU** [comment]
您好,如果用weibo数据集训练LSTM，要注意三点1.学习率要大一点1e-3左右（默认应该是5e-5 ）2. 指定一个中文词向量（默认是英文的）
3. No improve,参数设置大一点10这样子。
你也可以用bert-baee-chinese跑那个pretrained 模型。

**Comment by elaine35002** [comment]
您好，我試過1與2，2的中文向量我是用:
```
argument.add_argument('--word_vector', type=str, default=r'bert-base-chinese')
```
第三點，我看main.py程式碼預設已為10，就沒做更改了。 但這樣的改動AVG loss有明顯下降，且隨著訓練會逐步下降，但是F1 score仍皆為0，再麻煩作者解惑，或看能不能請您提供跑weibo數據集的code，感謝!!

**Comment by conglei2XU** [comment]
抱歉Ner_reader_cn弃用了，我没有删掉，您可以尝试直接使用ner_reader 方法试试

**Comment by elaine35002** [comment]
您好，我試出來結果仍為下圖所示:
![image](https://github.com/user-attachments/assets/385164d8-eac5-4914-8962-c500c1d3bccf)
想請問可以怎麼解決這個問題呢?或是當初您跑weibo dataset時具體是改哪些code呢 謝謝!

**Comment by conglei2XU** [comment]
刚刚我重新测试了LSTM 在weibo NER数据集的效果，基于[weibo词向量](https://github.com/Embedding/Chinese-Word-Vectors/tree/master) 模型在10epoch时F1值出现数值。F1一直为0的原因时没有给一个词向量导致模型训练的特别慢，后续建议使用bert-base-chinese等pretrained transformers然后选择mode 为 pretrained 运行weibo NER 数据集。因为数据集中一段话的标签是字符级别例如 ‘邓超今天去天津’ 对应的标签为‘B-PER I-PER O O O B-LOC I-LOC' 而在常规的词向量，邓超是一个完整的词，而NER任务中邓与超两个字的表示可能没有出现在词向量中，后续如果需要运行LSTM模型，最好使用一个字级别的词向量。
